// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt9vcKlfriLOC_fHM9UE9o1A0RFbB9--o',
    appId: '1:926038283509:web:ae550841077f7e5e8ba1bc',
    messagingSenderId: '926038283509',
    projectId: 'financeexpenses-a7536',
    authDomain: 'financeexpenses-a7536.firebaseapp.com',
    storageBucket: 'financeexpenses-a7536.appspot.com',
    measurementId: 'G-029S1NQTKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyUfSbaDWfs6LOlmcJYjaW1lXO3O2QOLE',
    appId: '1:926038283509:android:30c7f92de08486388ba1bc',
    messagingSenderId: '926038283509',
    projectId: 'financeexpenses-a7536',
    storageBucket: 'financeexpenses-a7536.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNO5wBi2wNydvWq2w512Vk7AX7uVbYT7I',
    appId: '1:926038283509:ios:2a6df0f54125721d8ba1bc',
    messagingSenderId: '926038283509',
    projectId: 'financeexpenses-a7536',
    storageBucket: 'financeexpenses-a7536.appspot.com',
    iosBundleId: 'com.example.financeExpenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNO5wBi2wNydvWq2w512Vk7AX7uVbYT7I',
    appId: '1:926038283509:ios:2a6df0f54125721d8ba1bc',
    messagingSenderId: '926038283509',
    projectId: 'financeexpenses-a7536',
    storageBucket: 'financeexpenses-a7536.appspot.com',
    iosBundleId: 'com.example.financeExpenses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt9vcKlfriLOC_fHM9UE9o1A0RFbB9--o',
    appId: '1:926038283509:web:e0434034bf72551c8ba1bc',
    messagingSenderId: '926038283509',
    projectId: 'financeexpenses-a7536',
    authDomain: 'financeexpenses-a7536.firebaseapp.com',
    storageBucket: 'financeexpenses-a7536.appspot.com',
    measurementId: 'G-8BY2G1CY5H',
  );
}
